1  # This workflow uses actions that are not certified by GitHub.
2  # They are provided by a third-party and are governed by
3  # separate terms of service, privacy policy, and support    
        with:
          # Argumentos adicionales para el SonarScanner CLI
          args:
            # 1. CLAVE DEL PROYECTO: (Tu clave exacta de SonarCloud)
            -Dsonar.projectKey=Stanleys-David_restaurantesaboresv2 
            
            # 2. CLAVE DE LA ORGANIZACIÓN: (Tu clave exacta de SonarCloud)
            -Dsonar.organization=stanleysdavid

          # Si comentaste alguna línea opcional como esta, revísala bien:
          #-Dsonar.sources=

          # Esta es la línea que debe estar alrededor de la línea 33, si la tenías:
          projectBaseDir: . 
          
